name: 'mkdocs sanity check'
on:
    push:
      branches:
        - main
#on: 
#  pull_request:
#    types: [opened, synchronize]
jobs:
  mkdocs-sanity-check:
    name: Check mkdocs builds successfully
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        architecture: x64

    - name: Install requirements
      run: python3 -m pip install -r requirements.txt

    - name: Install mkdocs-material
      run: python3 -m pip install mkdocs-material

    - name: Test mkdocs builds
      run: python3 -m mkdocs build

    - name: Checkout main
      uses: actions/checkout@v2

    - name: Deploy docs
      uses: AdminRedPanda/adminredpanda.github.io@main
      # Or use mhausenblas/mkdocs-deploy-gh-pages@nomaterial to build without the mkdocs-material theme
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CUSTOM_DOMAIN: adminredpanda.github.io
        CONFIG_FILE: mkdocs.yml
        EXTRA_PACKAGES: build-base
        # GITHUB_DOMAIN: github.myenterprise.com
        REQUIREMENTS: requirements.txt